[package]
name = "cargo-metadata"
version = "0.1.0"
authors = ["winger <isenbaev@gmail.com>"]

[dependencies]
docopt = "*"
rustc-serialize = "*"
toml = "*"

[dependencies.cargo]
git = "https://github.com/winger/cargo"

[[bin]]
name = "cargo-metadata"
test = false
doc = true
